### PR TITLE
Added support for HMAC signature.

### PR DESCRIPTION
**Pull request by jaheba**
This pull request adds support for Github's signature feature.

### CODE REVIEW

**Comment by ptersilie** [comment]
We also need to add the `SECRET = ''` to the config.template

**Comment by jaheba** [comment]
Right. The current approach allows to not have ``SECRET`` specified without causing an error. But I'll just add it to the config and then we can remove the ``getattr`` check.

**Comment by ptersilie** [comment]
That's a fair point. But I think by having it in the template it's more clear that it can be used.

**Comment by jaheba** [comment]
Should we add a config validation? So that all keys are tested for existance?

**Comment by ptersilie** [comment]
That would certainly make sense at some point when the config get's bigger. I don't feel its immediately necessary at the moment though, given the config and the people using the integration is fairly small at the moment. But feel free to add this in another PR if you are bored. ;)

**Comment by ptersilie** [comment]
Okay, can you squash this PR, then I will merge it. Did you test if the SECRET stuff is working in practise?

**Comment by jaheba** [comment]
Squash?

And yes, it is (hand) tested.

**Comment by ptersilie** [comment]
Squashing means combining some or all of the commits in this PR into a one to clean up the commit messages. For instance the "Typo" and my commit are not very useful. For this PR I would suggest quashing all commits into a single one with the commits message being the message from the first commit you made. See more here: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by jaheba** [comment]
Done

**Comment by ptersilie** [comment]
Looks good. Merged.

**Pull request merged**
