### PR TITLE
Update Pillow dependency.

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by vext01** [comment]
LGTM, but a test is failing on Python3.

```
__________ ERROR at setup of TestLiveServer.test_pull_request_review ___________

ScopeMismatch: You tried to access the 'function' scoped fixture 'app' with a 'session' scoped request object, involved factories

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/pytest_flask/fixtures.py:123:  def live_server(request, app, pytestconfig)

tests/conftest.py:4:  def app()

=========================== short test summary info ============================

ERROR tests/test_payloads.py::TestLiveServer::test_pull_request_review
```

**Comment by ptersilie** [comment]
I thought I fixed that. Ah, I pushed it to the wrong branch. Will fix later.

**Comment by ptersilie** [comment]
Let's see if this fixes things.

**Comment by vext01** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
