### PR TITLE
Development Updates

### PR DESCRIPTION
**Pull request by Theaxiom**
These updates are for Vagrant and Docker development, as well as encapsulating the Wiki support from GitHub.

### CODE REVIEW

**Comment by ptersilie** [comment]
Thanks for the PR. Would you mind elaborating a bit how Docker support has been improved and also explain what the vagrant support is for?

**Comment by Theaxiom** [comment]
Certainly; as for Docker, it wasn't working for me with the previous configuration. I have tested deployment on Docker Cloud, Kubernetes, Mesos, Docker Swarm and docker-compose, it is now all working across the board. As far as Vagrant support, I always do my development inside of Vagrant. Vagrant allows for a consistent development environment for all developers involved in the project. Let me know if you need any further details, I am continuing to bring additional improvements for this project. I primarily picked this up because I am maintaining http://mantl.io/ (https://github.com/mantl/mantl) and our primary development channel is on Mattermost.

**Comment by ptersilie** [comment]
I see. Thanks a lot for the docker stuff. That's really helpful. I'm not so sure about the Vagrant stuff and the `Contributing.md`. At the moment I don't really expect this project to become so big that it will be necessary to organise contributors. Most of the Github notifications are implemented with only some rare ones missing, and from then on it will probably just be minor maintenance work whenever something in Mattermost or Github changes.

I already merged the Wiki commits. If you put the Docker commits in a separate PR then I can merge that as well. We can then discuss the other additions on their own.

**Comment by Theaxiom** [comment]
You're more than welcome to edit my PR and remove whatever you don't want.
Good luck!

On Apr 10, 2017 7:40 AM, "Lukas Diekmann" <notifications@github.com> wrote:

I see. Thanks a lot for the docker stuff. That's really helpful. I'm not so
sure about the Vagrant stuff and the Contributing.md. At the moment I don't
really expect this project to become so big that it will be necessary to
organise contributors. Most of the Github notifications are implemented
with only some rare ones missing, and from then on it will probably just be
minor maintenance work whenever something in Mattermost or Github changes.

I already merged the Wiki commits. If you put the Docker commits in a
separate PR then I can merge that as well. We can then discuss the other
additions on their own.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/softdevteam/mattermost-github-integration/pull/31#issuecomment-292969825>,
or mute the thread

**Pull request closed without merging**
